import type {Metadata}
from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';

// Initialize MSW in development
if (process.env.NODE_ENV === 'development') {
    import ('@/mocks');
}

const geistSans = Geist({variable: '--font-geist-sans', subsets: ['latin']});

const geistMono = Geist_Mono({variable: '--font-geist-mono', subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({children} : Readonly < {
    children : React.ReactNode;
} >) {
    return (
        <html lang="en">
            <body classname={
                `${
                    geistSans.variable
                } ${
                    geistMono.variable
                } antialiased`
            }>
                {children} </body>
        </html>
    );
}
